### ISSUE TITLE
How to use postal.when in the browser using AMD

### ISSUE THREAD

**Issue by estaylorco** [postaljs/postal.when#2]
_(using 0.9.0)_

I've been using postal successfully for a while now, and I reach a point where I need the functionality in postal.when.  But I haven't been able to get it to work in a browser using AMD.

The example given on GitHub for AMD doesn't seem plausible: 3 modules are required, but only two are defined in the function arguments.  The example goes on to use "postal.when", but postal is never required (only its path is defined).  And 'postal.when' is required, but the path is never defined, nor does it show up in the function arguments.

How, exactly, do we use postal.when **under AMD and in a browser**?

Thank you.

**Comment by ifandelse** [comment]
Admittedly, it's been a while since I've look at postal.when - thanks for catching this....it's definitely a bug with the example. If I remember correctly, older versions of postal still put postal on the window even if it was in an AMD environment. postal.when was created back when that was the case, and it appears my example was making an ugly assumption that postal would magically be available on the window simply because postal.when takes postal as a dependency. So - I need to fix this! It's a super easy fix, so I'll try and do it tonight and post an update here....

**Comment by ifandelse** [comment]
@estaylorco Ok - give v0.2.0 a try - I've updated the UMD wrapper and tested in node and in the browser with both requireJS and plain vanilla script tags. I'll keep this open until I hear back...thanks!

**Comment by estaylorco** [comment]
@ifandelse Thanks for getting back to me.  O.K., so this is the line I have a problem with:

```
require( ['jquery', 'underscore', 'postal', 'postal.when'], function ( $, _, postal ) ...
```

Isn't the function missing an argument?  We have 4 requires but only 3 arguments.

**Comment by ifandelse** [comment]
The postal.when plugin adds functionality to postal itself, so you don't have to worry about a return value on it's module (though it's actually returning postal). In requireJS, once a module ID has been resolved, the same return value is used for any further requests for that module. so regardless of which resolves first - the postal in the line above, OR the postal in postal.when's dependencies, postal.when just adds the when method to postal itself - effectively modifying the postal module's return value - hopefully that makes sense :-).

Technically, postal.when is returning postal as well, so you could in theory leave off postal above and just require postal.when, but I never do that b/c it can be confusing to someone not familiar with postal and it's add-ons, or requireJS (plus, other postal add-ons follow the same approach of modifying postal this way also).

FWIW - if you ever use postal in node.js, the CommonJS module situation is a bit different than AMD....and the CommonJS module for postal.when returns a factory method, to which you pass postal. RequireJS handles that part for us by nature of its design...

**Comment by estaylorco** [comment]
Yes, actually, it does make sense, and now I have gotten it to work!  Thanks for the insight.  Oh, and coincidentally, just when I received an email informing me of your response above, I was reading _Seven JavaScript Quirks I Wish I'd Known About_ on FlipBoard (my most favorite app in the whole world).  Great article, and thanks for the insight there, too!

**Comment by ifandelse** [comment]
Nice! I agree - flipboard is an awesome app. I set up a completely time-killing workflow using flipboard, instapaper and evernote at one point....and managed to swamp myself with probably 100 years worth of reading :-S
