### ISSUE TITLE
Not published to Bower registry

### ISSUE THREAD

**Issue by adamshaylor** [postaljs/postal.when#5]
You can install via the repo’s URL, of course.

**Comment by ifandelse** [comment]
Thanks @adamshaylor - apologies for the delay. Been heads-down on some other projects. Will try to get this taken care of ASAP.

**Comment by adamshaylor** [comment]
No problem. I’d be happy to do this for you and PR it if it were that sort of issue. Loving postal.js, btw. :smiley:

**Comment by adamshaylor** [comment]
Looks like anyone can do this so I did it.

**Comment by ifandelse** [comment]
@adamshaylor DOH! I let this one slip through the cracks. I blame it on lack of sleep due to 15 month old son. That's legit, right? :) Thanks for publishing it.

**Comment by adamshaylor** [comment]
Happy to help. I have a two year old, so I know what it’s like.
